---
- hosts: all
  become: yes
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Disable swap
    command: swapoff -a

  - name: Delete swapfile
    file:
      name: /swapfile
      state: absent

  - name: start Docker
    service:
      name: docker
      state: started
    notify:
    - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: start kubelet
    service:
      name: kubelet
      enabled: yes
      state: started

  - name: Configure node ip
    lineinfile:
      path: /etc/default/kubelet
      create: yes
      line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="10.10.1.10" --apiserver-cert-extra-sans="10.10.1.10"  --node-name k8s-master --pod-network-cidr=10.10.0.0/16

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  - name: Get url
    become: no
    get_url:
      url: https://docs.projectcalico.org/v3.12/manifests/calico.yaml
      force: yes
      dest: /home/vagrant/calico-new.yaml
  - name: modify calico-new.yaml
    become: no
    shell: > 
      #sed -i 's/            # - name: CALICO_IPV4POOL_CIDR/            - name: CALICO_IPV4POOL_CIDR\n              value: "10.10.0.0\/16/' calico-new.yaml;
      sed -i 's/              value: "192.168.0.0\/16"/              value: "10.10.0.0\/16"/g' calico-new.yaml;
      sed -i 's/              value: "Always"/              value: "Never"/g' calico-new.yaml;
      sleep 2;
      kubectl apply -f calico-new.yaml;
    register: stdout

  - name: debug output
    debug: msg={{ stdout }}
    
    
  handlers:
  - name: docker status
    service: name=docker state=started
