routerid: 172.16.255.103
hostname: leaf-sw3.lab.local

loopbacks:
  - name: lo
    ipv4: 172.16.255.103/32

interfaces:    
  - name: swp1
  - name: swp2

bridges:
  - name: VLAN10
    ipv4: 10.50.3.1/24
    ports:
      - swp3

bgp:
  as: 65103
  routerid: 172.16.255.103
  clusterid: 172.16.255.103
  ipv4_unicast_redistribute:
    - route_map: CONNECTED_TO_BGP
      type: connected  
  ipv4_unicast_peers:
    - interface: swp1
      softinbound: true
    - interface: swp2
      softinbound: true

  ipv4_unicast_peer_groups:
    - group_name: K8S-NODES
      group_as: 65103
      group_range: 10.50.3.0/24
      rr_client: true
      next_hop_self: true
      softinbound: true

routemaps:
  - name: CONNECTED_TO_BGP
    action: permit
    order: 10
    statement: "match interface lo"
  - name: CONNECTED_TO_BGP
    action: permit
    order: 20
    statement: "match interface VLAN10"
  - name: CONNECTED_TO_BGP
    action: deny
    order: 65535
    statement: ""
