---
# Global BGP configuration. Disable node-to-node mesh

apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false

---
# Per-node configuration

apiVersion: projectcalico.org/v3
kind: Node
metadata:
  labels:
    rack: rack1
  name: k8s-master
spec:
  bgp:
    asNumber: 65101
    ipv4Address: 10.50.1.10/24
---
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  labels:
    rack: rack2
  name: k8s-worker-1
spec:
  bgp:
    asNumber: 65102
    ipv4Address: 10.50.2.10/24
---
apiVersion: projectcalico.org/v3
kind: Node
metadata:
  labels:
    rack: rack3
  name: k8s-worker-2
spec:
  bgp:
    asNumber: 65103
    ipv4Address: 10.50.3.10/24

---
# BGP peer configuration.

apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack1-tor
spec:
  peerIP: 10.50.1.1
  asNumber: 65101
  nodeSelector: rack == 'rack1'
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack2-tor
spec:
  peerIP: 10.50.2.1
  asNumber: 65102
  nodeSelector: rack == 'rack2'
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack3-tor
spec:
  peerIP: 10.50.3.1
  asNumber: 65103
  nodeSelector: rack == 'rack3'
---
