Vagrant.configure("2") do |config|
    config.ssh.insert_key = false

    #
    # Kubernetes nodes
    #

    config.vm.define "k8s-master" do |master|
        master.vm.box = "k8s-baseos"
        master.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
        end
        master.vm.hostname = "k8s-master"
        master.vm.network "private_network", ip: "10.10.1.10"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible-k8s/master.yaml"
            verbose = true
            ansible.extra_vars = {
                node_ip: "10.10.1.10",
            }
        end
    end

    config.vm.define "k8s-worker-1" do |worker|
        worker.vm.box = "k8s-baseos"
        worker.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end
        worker.vm.hostname = "k8s-worker-1"
        worker.vm.network "private_network", ip: "10.10.1.20"
        worker.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible-k8s/worker.yaml"
            verbose = true
            ansible.extra_vars = {
                node_ip: "10.10.1.20",
            }
        end
    end

    config.vm.define "k8s-worker-2" do |worker|
        worker.vm.box = "k8s-baseos"
        worker.vm.provider "virtualbox" do |v|
            v.memory = 1024
            v.cpus = 1
        end
        worker.vm.hostname = "k8s-worker-2"
        worker.vm.network "private_network", ip: "10.10.1.30"
        worker.vm.provision "ansible" do |ansible|
            ansible.playbook = "ansible-k8s/worker.yaml"
            verbose = true
            ansible.extra_vars = {
                node_ip: "10.10.1.30",
            }
        end
    end

end

