---
# Global BGP configuration. Disable node-to-node mesh

apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: false

---
# BGP peer configuration.

apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack1-tor1
spec:
  peerIP: 10.50.1.1
  asNumber: 65101
  nodeSelector: rack == 'rack1'
  sourceAddress: None
  failureDetectionMode: BFDIfDirectlyConnected
  restartMode: LongLivedGracefulRestart
  birdGatewayMode: DirectIfDirectlyConnected
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack1-tor2
spec:
  peerIP: 10.50.2.1
  asNumber: 65101
  nodeSelector: rack == 'rack1'
  sourceAddress: None
  failureDetectionMode: BFDIfDirectlyConnected
  restartMode: LongLivedGracefulRestart
  birdGatewayMode: DirectIfDirectlyConnected
---

apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack2-tor1
spec:
  peerIP: 10.50.3.1
  asNumber: 65102
  nodeSelector: rack == 'rack2'
  sourceAddress: None
  failureDetectionMode: BFDIfDirectlyConnected
  restartMode: LongLivedGracefulRestart
  birdGatewayMode: DirectIfDirectlyConnected
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: rack2-tor2
spec:
  peerIP: 10.50.4.1
  asNumber: 65102
  nodeSelector: rack == 'rack2'
  sourceAddress: None
  failureDetectionMode: BFDIfDirectlyConnected
  restartMode: LongLivedGracefulRestart
  birdGatewayMode: DirectIfDirectlyConnected
---

