# This section includes base Calico Enterprise installation configuration.
# For more information, see: https://docs.tigera.io/v2.8/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
      - cidr: 10.10.0.0/16
        encapsulation: "None"
        natOutgoing: "Disabled"
    nodeAddressAutodetectionV4:
      interface: lo

  variant: TigeraSecureEnterprise
  clusterManagementType: Standalone
  imagePullSecrets:
    - name: tigera-pull-secret

---


---

# This section installs and configures the Calico Enterprise API server.
# For more information, see: https://docs.tigera.io/v2.8/reference/installation/api#operator.tigera.io/v1.APIServer
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: tigera-secure

---

