Vagrant.configure("2") do |config|
  config.vm.define "source", autostart: false do |source|
	source.vm.box = "geerlingguy/ubuntu1804"
	config.ssh.insert_key = false
  end
  config.vm.define "output" do |output|
	output.vm.box = "k8snode"
	output.vm.box_url = "file://package.box"
	config.ssh.insert_key = false
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
end